game/urls.py
from django.urls import path
from .views import home_view, public_card_list_view, private_card_list_view, card_search_view, card_query_view,\
    deck_list_view, deck_detail_view, DeckCreateView,\
    MonsterCardCreateView, monster_card_update_view,\
    spell_card_create_view, monster_card_detail_view, spell_card_detail_view, \
    deck_add_monster_card_view, \
    room_list_view, room_view, host_view, \
    register_view, \
    user_settings_view

app_name = 'game'  # URL namespace for this app
urlpatterns = [
    path('', home_view, name='home'),

    # MonsterCard
    path('create_monster_card/', MonsterCardCreateView.as_view(), name='create_monster_card'),
    path('<int:pk>/monster_card_update/', monster_card_update_view, name='monster_card_update'),

    path('spell_card_create/', spell_card_create_view, name='spell_card_create'),

    path('<int:pk>/monster_card_detail/', monster_card_detail_view, name='monster_card_detail'),
    path('<int:pk>/spell_card_detail/', spell_card_detail_view, name='spell_card_detail'),

    path('public_card_list/', public_card_list_view, name='public_card_list'),
    path('private_card_list/', private_card_list_view, name='private_card_list'),
    path('card_search/', card_search_view, name='card_search'),
    path('card_query', card_query_view, name='card_query'),

    # Deck
    path('deck_create/', DeckCreateView.as_view(), name='deck_create'),
    path('deck_list/', deck_list_view, name='deck_list'),
    path('<int:pk>/deck_detail/', deck_detail_view, name='deck_detail'),
    path('deck_add_monster_card/', deck_add_monster_card_view, name='deck_add_monster_card'),

    # GameState
    path('host/', host_view, name='host'),
    path('register/', register_view, name='register'),
    path('room_list/', room_list_view, name='room_list'),
    # TODO: <slug> potentially dangerous
    path('room/<slug:room_name>/', room_view, name='room'),

    # UserSettings
    path('user_settings/', user_settings_view, name='user_settings'),
]

game/templates/game/card_create.html
{% extends 'base.html' %}

{% block title %}
    Create Card
{% endblock %}

{% block content %}
    <div class="container">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>

    </div>

{% endblock %}

game/templates/game/card_detail.html
{% extends 'base.html' %}

{% block title %}
    {% if card %}
        {{ card.name }}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">

    {% if card %}
        {# Card Name #}
        <p>Name: {{ card.name }}</p>
        <p>Creator: {{ card.creator }}</p>

        {# Add this card to a deck #}
        <p>Add this card to a deck</p>
        {% if decks %}
            <select class="add-card-select"
                    data-add-card-url="{% url 'game:deck_add_monster_card' %}"
            >
            <option disabled selected value> -- select an option -- </option>
            {% for deck in decks %}
                <option class="add-card-option"
                        value="{{ deck.pk }}">{{ deck.name }}</option>
            {% endfor %}
            </select>
            <button id="add-card-submit-button" type="submit">Add to Deck</button>
        {% endif %}

        {# Edit this card #}
        {#    TODO: Will not work for non monster cards    #}
        <p><a href="{% url 'game:monster_card_update' card.pk %}">Edit this card</a></p>

    {% endif %}

    </div>

{% endblock %}

{% block javascript %}
    <script>
        let select = $('.add-card-select');
        let submit = $('#add-card-submit-button');
        let deckPk;

        // Add a change event listener to select that adds the card to the specified deck (using deck.pk)
        select.change(function () {
            deckPk = $(this).val()
        });

        submit.click(function () {
            let option = select.children('option:selected');
            $.ajax({
                url: select.attr('data-add-card-url'),
                method: 'POST',
                headers: {'X-CSRFToken': '{{ csrf_token }}'},
                data: {
                    deckPk: deckPk,
                    cardPk: {{ card.pk }},
                },
                success: function (data) {
                    if (data.success) {
                        alert('Card successfully added to deck')
                    } else {
                        alert('Error: Card not added to deck')
                    }
                }

            })

            // window.location = option.attr('data-add-card-url');  // Get request and makes the browser load this page
        })


    </script>
{% endblock %}

game/templates/game/card_list.html
{% extends 'base.html' %}

{% block title %}
    List of Cards
{% endblock %}

{% block content %}
    <div class="container">
    <table id="select-card-type-table">
        <tr>
            <th>Select Card Type</th>
{#            <th>Select Deck to Add to</th>#}
        </tr>
        <tr>
            <td>
                <select id="card-select">
                    <option disabled selected value> -- select an option -- </option>
                    <option id="monster-option" value="monster">monster</option>
                    <option id="spell-option" value="spell">spell</option>
                </select>
            </td>
{#            <td>#}
{#                <select id="deck-select">#}
{#                    <option disabled selected value> -- select an option -- </option>#}
{#                    {% for deck in decks %}#}
{#                        <option id="deck-{{ deck.pk }}-option" class="deck-option" value="{{ deck.pk }}">{{ deck.name }}</option>#}
{#                    {% endfor %}#}
{#                </select>#}
{#            </td>#}
        </tr>
    </table>

    <table id='monster-table' style="display:none">
        <tr>
            <th>Creator</th>
            <th>Name</th>
            <th>Description</th>
            <th>Cost</th>
            <th>HP</th>
            <th>Attack</th>
            {% if deck %}
                <th>Add to {{ deck.name }}</th>
            {% endif %}
        </tr>

        {% for monster in monsters %}
        <tr>
            <td>{{ monster.creator }}</td>
            <td><a href="{% url 'game:monster_card_detail' monster.pk %}">{{ monster.name }}</a></td>
            <td>{{ monster.description }}</td>
            <td>{{ monster.cost }}</td>
            <td>{{ monster.hp }}</td>
            <td>{{ monster.attack }}</td>
        </tr>
        {% endfor %}
    </table>

    <table id='spell-table' style="display:none">
        <tr>
            <th>Creator</th>
            <th>Name</th>
            <th>Description</th>
            <th>Cost</th>
            <th>Effect</th>
        </tr>

        {% for spell in spells %}
        <tr>
            <td>{{ spell.creator }}</td>
            <td><a href="{% url 'game:spell_card_detail' spell.pk %}">{{ spell.name }}</a></td>
            <td>{{ spell.description }}</td>
            <td>{{ spell.cost }}</td>
            <td>{{ spell.effect }}</td>
        </tr>
        {% endfor %}
    </table>



{#    {% for card in object_list %}#}
{#        ID: {{ card.id }}, Cost: {{ card.cost }}, Description:{{ card.description }}, Name: {{ card.name }}<br>#}
{#    {% endfor %}#}
    </div>
{% endblock %}



{% block javascript %}
    <script>
        let cardSelect = $('#card-select');
        let monsterTable = $('#monster-table');
        let spellTable = $('#spell-table');

        // Show what user what he chooses to see
        cardSelect.change(function () {
            if ($(this).val() === 'monster') {
                monsterTable.show();
                spellTable.hide();
            }
            else if ($(this).val() === 'spell') {
                monsterTable.hide();
                spellTable.show();
            }
        });

    </script>
{% endblock %}

game/templates/game/card_search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Search for a Card
{% endblock %}

{% block content %}
    <div class="container">
        <!-- Search form -->
        <div class="md-form mt-0">
            <input id="searchbar" data-card-query-url="{% url 'game:card_query' %}" class="form-control" type="text" placeholder="Search" aria-label="Search">
        </div>

        <div class="row">
            <div class="col col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <ul id="monster-card-list"></ul>
            </div>
            <div class="col col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <ul id="spell-card-list"></ul>
            </div>
        </div>

    </div>
{% endblock %}

{% block style %}
{% endblock %}

{% block javascript %}
    <script src="{% static 'game/card_search.js' %}"></script>
{% endblock %}

game/templates/game/deck_create.html
{% extends 'base.html' %}

{% block title %}
    Create a Deck
{% endblock %}

{% block content %}
    <div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
    </div>
{% endblock %}

game/templates/game/deck_detail.html
{% extends 'base.html' %}
{% block title %}
    Deck Details
{% endblock %}

{% block content %}
    <div class="container">

    {% if deck %}
        <p>{{ deck.name }}</p>
    {% endif %}

    {% for monster_card in monster_cards %}
        {{ monster_card.name }}
    {% endfor %}

    {% for spell_card in spell_cards %}
        {{ spell_card.name }}
    {% endfor %}

    </div>
{% endblock %}

game/templates/game/deck_list.html
{% extends 'base.html' %}

{% block title %}
    List of Decks
{% endblock %}

{% block content %}
    <div class="container">
    <p><a href="{% url 'game:deck_create'%}">Create a new deck</a></p>

    {% for deck in decks %}
        <div><a href="{% url 'game:deck_detail' deck.pk %}">{{ deck.name }}</a></div>
    {% endfor %}
    </div>
{% endblock %}

game/templates/game/gamestate_create.html
{% extends 'base.html' %}

{% block title %}
    Host a Game
{% endblock %}

{% block content %}
    <div class="container">
    <p>Only numbers, letters, underscores and hyphens are allowed.</p>
    <form method="POST" action="{% url 'game:host' %}">
        {% csrf_token %}
        {{ form.as_p }}
    </form>
    </div>
{% endblock %}

game/templates/game/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}

{# {% url 'url_name as specified in urls' %}  #}
    <div class="container">
        <p><a href="{% url 'game:public_card_list' %}">View Public Cards</a></p>
        <p><a href="{% url 'game:private_card_list' %}">{{ request.user }}</a></p>
        <p><a href="{% url 'game:card_search' %}">Search Cards</a></p>
        <p><a href="{% url 'game:deck_list' %}">Manage Decks</a></p>
        <p><a href="{% url 'game:create_monster_card' %}">Create a Monster Card</a></p>
        <p><a href="{% url 'game:spell_card_create' %}">Create a Spell Card</a></p>
        <p><a href="{% url 'game:room_list' %}">View active Games</a></p>
        <p><a href="{% url 'game:host' %}">Create a Game</a></p>
        <p><a href="{% url 'game:user_settings' %}">Manage User Settings</a></p>


{#    <p>Host a game</p>#}
{#    <input id="host-room-name-input" class="input-text" type="text">#}
{#    <input id="host-room-name-submit" type="submit">#}

    <p>Join a game</p>
    <input id="join-room-name-input" class="input-text" type="text">
    <input id="join-room-name-submit" type="submit">

    </div>


    {# TODO Users can create a new game by selecting a another User they wish to play with #}

{% endblock %}

{% block javascript %}
    <script>
        {#let hostSubmit = $('#host-room-name-submit');#}
        {#let hostInput = $('#host-room-name-input');#}
        let joinSubmit = $('#join-room-name-submit');
        let joinInput = $('#join-room-name-input');

        /*
        hostInput.keyup(function (e) {
            if (e.keyCode === 13) {
                hostSubmit.click();
            }
        });
        hostSubmit.click(function () {
            window.location.pathname = window.location.pathname + 'host/' + hostInput.val()
        });
        */

        joinInput.focus();
        joinInput.keyup(function (e) {
            if (e.keyCode === 13) {
                joinSubmit.click();
            }
        });
        joinSubmit.click(function () {
            window.location.pathname = window.location.pathname + 'room/' + joinInput.val()
        });

    </script>
{% endblock %}

game/templates/game/room.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {% if player_1_name %}{{ player_1_name }}{% else %}Player 1{% endif %}
        vs
    {% if player_2_name %}{{ player_2_name }}{% else %}Player 2{% endif %}
{% endblock %}

{% block content %}
    <h1 id="winner"></h1>


    <b>Players</b>
    <table id="player-table">
        <tr>
            <td id="player-1">
                <div id="player-1-profile-picture" class="portrait">
                    <img src="{{ player_1_settings.profile_picture.url }}">
                </div>
                <div id="player-1-name">{{ player_1_name }}</div>
                HP: <div id="player-1-hp">{{ player_1_hp }}</div>
                Mana: <div id="player-1-mana">{{ player_1_mana }}</div>
                Max Mana: <div id="player-1-max-mana">{{ player_1_max_mana }}</div>
                Cards in Deck:<div id="player-1-deck-counter"></div>
            </td>
            <td id="player-2">
                <div id="player-2-profile-picture" class="portrait">
                    <img src="{{ player_2_settings.profile_picture.url }}">
                </div>
                <div id="player-2-name">{{ player_2_name }}</div>
                HP: <div id="player-2-hp">{{ player_2_hp }}</div>
                Mana: <div id="player-2-mana">{{ player_2_mana }}</div>
                Max Mana: <div id="player-2-max-mana">{{ player_2_max_mana }}</div>
                Cards in Deck:<div id="player-2-deck-counter"></div>
            </td>
        </tr>

{#            <th><div id="player-1-name">{{ player_1_name }}</div></th>#}
{#            <th><div id="player-2-name">{{ player_2_name }}</div></th>#}
{##}
{#            <td>HP: <div id="player-1-hp">{{ player_1_hp }}</div></td>#}
{#            <td>HP: <div id="player-2-hp">{{ player_2_hp }}</div></td>#}
{##}
{#            <td>Mana: <div id="player-1-mana">{{ player_1_mana }}</div></td>#}
{#            <td>Mana: <div id="player-2-mana">{{ player_2_mana }}</div></td>#}
{##}
{#            <td>Max Mana: <div id="player-1-max-mana">{{ player_1_max_mana }}</div></td>#}
{#            <td>Max Mana: <div id="player-2-max-mana">{{ player_2_max_mana }}</div></td>#}
{##}
{#            <td>Cards in Deck:<div id="player-1-deck-counter"></div></td>#}
{#            <td>Cards in Deck:<div id="player-2-deck-counter"></div></td>#}
    </table>


{# Try 1 #}
{#<div class="container-fluid">#}
{#  <div class="row">#}
{#    <div class="card-group">#}
{#    {% for i in '0123456' %}#}
{##}
{#      <div class="card player-1-field-card" data-player-1-field-card="{{ i }}">#}
{##}
{#        <div class="card-body">#}
{##}
{#            <div class="position">{{ i }}</div>#}
{#            <h5 class="card-title name"></h5>#}
{#        </div>#}
{#        <img class="picture" src="">#}
{#        <div class="card-body">#}
{#            <small class="text-muted"><p class="card-text description"></p></small>#}
{#            <span class="card-text cost"></span>#}
{#            <span class="card-text attack"></span>#}
{#            <span class="card-text hp"></span>#}
{#        </div>#}
{##}
{#      </div>#}
{#    {% endfor %}#}
{#    </div>#}
{#  </div>#}
{#</div>#}



    <b>Field</b>
    <table id="field-table">
        <tr>
            <th></th>

            {% for i in '0123456' %}
                <th>Monster {{ i }}</th>
            {% endfor %}
        </tr>

        <tr>
            <th>{{ player_1_name }}</th>

            {% for i in '0123456' %}
                <td>
                    <div class="card player-1-field-card"
                         data-player-1-field-card="{{ i }}">
                        <div class="position">{{ i }}</div>
                        <div class="name"></div>
                        <img class="picture portrait">
                        <div class="description"></div>
                        <div class="cost"></div>
                        <div class="attack"></div>
                        <div class="hp"></div>
                    </div>
                </td>
            {% endfor %}
        </tr>
        <tr>
            <th>{{ player_2_name }}</th>

            {% for i in '0123456' %}
                <td>
                    <div class="card player-2-field-card"
                         data-player-2-field-card="{{ i }}">
                        <div class="position">{{ i }}</div>
                        <div class="name"></div>
                        <img class="picture portrait">
                        <div class="description"></div>
                        <div class="cost"></div>
                        <div class="attack"></div>
                        <div class="hp"></div>
                    </div>
                </td>
            {% endfor %}
        </tr>
    </table>

    <b>Hand</b>
    <table id="hand-table">
        <tr>
            {% for i in '0123456789' %}
                <td>
                    <div class="card hand-card"
                        data-hand-card="{{ i }}">
                        <div class="position">{{ i }}</div>
                        <div class="name"></div>
                        <img class="picture portrait">
                        <div class="description"></div>
                        <div class="cost"></div>
                    </div>
                </td>

            {% endfor %}
        </tr>
    </table>



    <button id="start-game-button">Start Game</button>
    <button id="end-turn-button">End Turn</button>
    <button id="surrender-button">Surrender</button>
    <button id="delete-game">Delete Game</button>
    <button id="summon-button">Summon</button>
    <button id="attack">Attack</button>

    <div>Turn:
        <div id="turn"></div>
    </div>

    <br>

    <textarea id="chat-log" cols="100" rows="10"></textarea><br>
    <input id="chat-input">
    <input id="chat-submit" type="submit">


{% endblock %}


{% block javascript %}

    <script>
        let roomName = '{{ room_name }}';
        let username = '{{ request.user.username }}';
        let player1Name = '{{ player_1_name }}';
        let player2Name = '{{ player_2_name }}';
    </script>

    <script src="{% static 'game/room.js' %}"></script>

{% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'game/room.css' %}">
{% endblock %}

game/templates/game/room_list.html
{% extends 'base.html' %}

{% block title %}
    Room List
{% endblock %}
{% block content %}
    <div class="container">
    <p>List of Active Rooms</p>

    <table>
        <tr>
            <th>Room</th>
            <th>{{ game.player_1.username }}</th>
            <th>{{ game.player_2.username }}</th>
            <th>Register</th>
        </tr>

        {% for room in rooms %}
            <tr>
                <td><a href="{% url 'game:room' room.room_name %}">{{ room.room_name }}</a></td>
                <td>{{ room.player_1_name }}</td>
                <td>{{ room.player_2_name }}</td>
                <td>
                    <form method="POST" action="{% url 'game:register' %}">
                        {% csrf_token %}
                        <input name="room_name" value="{{ room.room_name }}" style="display:none">
                        <input type="submit" value="Register">
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
    </div>
{% endblock %}

{% block javascript %}
    <script>
    </script>
{% endblock %}

game/templates/game/user_settings.html
{% extends 'base.html' %}

{% block title %}
    User Settings
{% endblock %}

{% block content %}
    <div class="container">
    <form method="POST" action="{% url 'game:user_settings' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>

    {% if user_settings.profile_picture %}
        <img src="{{ user_settings.profile_picture.url }}">
    {% endif %}
    </div>
{% endblock %}